// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bidder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` //(FAIL; SUCCESS; EXCEPTION) //or int32
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bidder) Reset() {
	*x = Bidder{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bidder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bidder) ProtoMessage() {}

func (x *Bidder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bidder.ProtoReflect.Descriptor instead.
func (*Bidder) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Bidder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MyBid         int32                  `protobuf:"varint,1,opt,name=my_bid,json=myBid,proto3" json:"my_bid,omitempty"`
	MyId          int32                  `protobuf:"varint,2,opt,name=my_id,json=myId,proto3" json:"my_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetMyBid() int32 {
	if x != nil {
		return x.MyBid
	}
	return 0
}

func (x *BidResponse) GetMyId() int32 {
	if x != nil {
		return x.MyId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HigestBid     int32                  `protobuf:"varint,1,opt,name=higest_bid,json=higestBid,proto3" json:"higest_bid,omitempty"`
	ItemSold      bool                   `protobuf:"varint,2,opt,name=item_sold,json=itemSold,proto3" json:"item_sold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetHigestBid() int32 {
	if x != nil {
		return x.HigestBid
	}
	return 0
}

func (x *ResultResponse) GetItemSold() bool {
	if x != nil {
		return x.ItemSold
	}
	return false
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\x12\x05proto\" \n" +
	"\x06Bidder\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"9\n" +
	"\vBidResponse\x12\x15\n" +
	"\x06my_bid\x18\x01 \x01(\x05R\x05myBid\x12\x13\n" +
	"\x05my_id\x18\x02 \x01(\x05R\x04myId\"\a\n" +
	"\x05Empty\"L\n" +
	"\x0eResultResponse\x12\x1d\n" +
	"\n" +
	"higest_bid\x18\x01 \x01(\x05R\thigestBid\x12\x1b\n" +
	"\titem_sold\x18\x02 \x01(\bR\bitemSold2\xe2\x02\n" +
	"\x0eAuctionService\x12*\n" +
	"\x03Bid\x12\r.proto.Bidder\x1a\x12.proto.BidResponse\"\x00\x12/\n" +
	"\x06Result\x12\f.proto.Empty\x1a\x15.proto.ResultResponse\"\x00\x12)\n" +
	"\tSetLeader\x12\f.proto.Empty\x1a\f.proto.Empty\"\x00\x12/\n" +
	"\x0fPublicSetLeader\x12\f.proto.Empty\x1a\f.proto.Empty\"\x00\x12/\n" +
	"\x0fSetSyncFollower\x12\f.proto.Empty\x1a\f.proto.Empty\"\x00\x126\n" +
	"\x16PublishSetSyncFollower\x12\f.proto.Empty\x1a\f.proto.Empty\"\x00\x12.\n" +
	"\x0eUpdateDatabase\x12\f.proto.Empty\x1a\f.proto.Empty\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_proto_goTypes = []any{
	(*Bidder)(nil),         // 0: proto.Bidder
	(*BidResponse)(nil),    // 1: proto.BidResponse
	(*Empty)(nil),          // 2: proto.Empty
	(*ResultResponse)(nil), // 3: proto.ResultResponse
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: proto.AuctionService.Bid:input_type -> proto.Bidder
	2, // 1: proto.AuctionService.Result:input_type -> proto.Empty
	2, // 2: proto.AuctionService.SetLeader:input_type -> proto.Empty
	2, // 3: proto.AuctionService.PublicSetLeader:input_type -> proto.Empty
	2, // 4: proto.AuctionService.SetSyncFollower:input_type -> proto.Empty
	2, // 5: proto.AuctionService.PublishSetSyncFollower:input_type -> proto.Empty
	2, // 6: proto.AuctionService.UpdateDatabase:input_type -> proto.Empty
	1, // 7: proto.AuctionService.Bid:output_type -> proto.BidResponse
	3, // 8: proto.AuctionService.Result:output_type -> proto.ResultResponse
	2, // 9: proto.AuctionService.SetLeader:output_type -> proto.Empty
	2, // 10: proto.AuctionService.PublicSetLeader:output_type -> proto.Empty
	2, // 11: proto.AuctionService.SetSyncFollower:output_type -> proto.Empty
	2, // 12: proto.AuctionService.PublishSetSyncFollower:output_type -> proto.Empty
	2, // 13: proto.AuctionService.UpdateDatabase:output_type -> proto.Empty
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
