// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RA_SendArrivalAnnouncement_FullMethodName   = "/proto.RA/SendArrivalAnnouncement"
	RA_GiveCriticalSectionAccess_FullMethodName = "/proto.RA/GiveCriticalSectionAccess"
)

// RAClient is the client API for RA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAClient interface {
	SendArrivalAnnouncement(ctx context.Context, in *ArrivalAnnouncement, opts ...grpc.CallOption) (*Empty, error)
	GiveCriticalSectionAccess(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rAClient struct {
	cc grpc.ClientConnInterface
}

func NewRAClient(cc grpc.ClientConnInterface) RAClient {
	return &rAClient{cc}
}

func (c *rAClient) SendArrivalAnnouncement(ctx context.Context, in *ArrivalAnnouncement, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RA_SendArrivalAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAClient) GiveCriticalSectionAccess(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RA_GiveCriticalSectionAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAServer is the server API for RA service.
// All implementations must embed UnimplementedRAServer
// for forward compatibility.
type RAServer interface {
	SendArrivalAnnouncement(context.Context, *ArrivalAnnouncement) (*Empty, error)
	GiveCriticalSectionAccess(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRAServer()
}

// UnimplementedRAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAServer struct{}

func (UnimplementedRAServer) SendArrivalAnnouncement(context.Context, *ArrivalAnnouncement) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendArrivalAnnouncement not implemented")
}
func (UnimplementedRAServer) GiveCriticalSectionAccess(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveCriticalSectionAccess not implemented")
}
func (UnimplementedRAServer) mustEmbedUnimplementedRAServer() {}
func (UnimplementedRAServer) testEmbeddedByValue()            {}

// UnsafeRAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAServer will
// result in compilation errors.
type UnsafeRAServer interface {
	mustEmbedUnimplementedRAServer()
}

func RegisterRAServer(s grpc.ServiceRegistrar, srv RAServer) {
	// If the following call pancis, it indicates UnimplementedRAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RA_ServiceDesc, srv)
}

func _RA_SendArrivalAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArrivalAnnouncement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServer).SendArrivalAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RA_SendArrivalAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServer).SendArrivalAnnouncement(ctx, req.(*ArrivalAnnouncement))
	}
	return interceptor(ctx, in, info, handler)
}

func _RA_GiveCriticalSectionAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServer).GiveCriticalSectionAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RA_GiveCriticalSectionAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServer).GiveCriticalSectionAccess(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RA_ServiceDesc is the grpc.ServiceDesc for RA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RA",
	HandlerType: (*RAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendArrivalAnnouncement",
			Handler:    _RA_SendArrivalAnnouncement_Handler,
		},
		{
			MethodName: "GiveCriticalSectionAccess",
			Handler:    _RA_GiveCriticalSectionAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
